### PR TITLE
Bug/158

### LINKED ISSUE #158: Validate > error messages can be overwhelming on screen reader when multiple validation errrors
Inline error messages are rendered to elements with role=alert. When there are multiple validation errors they are all announced at the same by the screen reader.

A proposed solution is to remove the role=alert attribute from each inline error message container and generate a single visually hidden role=alert container that lists all validation errors so they are announced sequentially once.

### PR DESCRIPTION
**Pull request by sarah-storm**
Fixes #158.  

Update to the error messaging as follows:

- Server error message nodes, and inserted errors within labels are still used, but with role="alert" removed

- A summary div with role="alert" is added at the top of the form.  Requires the CSS in the site to hide it in an accessible manner, otherwise it could be styled as an overall error summary for the form.

- Error spans are added to this summary at the point of validation.  These are connected to the original input by means of a data attribute matching the group name so that they can be selectively removed later.

- Tests updated and added to support this.

### CODE REVIEW

**Comment by sarah-storm** [comment]
Latest update includes an option to enable the new functionality in the settings for backwards compatibility:

useSummary : true

Also includes an update to the ReadMe and tests to match the new setting.   I have copied these changes back into a local project.  Initial tests of the original PR were working well in NVDA/Chrome, but I intend to upload a version which I can access on an iOS device to test VO.

**Comment by sarah-storm** [comment]
Have run into this issue:

https://github.com/nvaccess/nvda/issues/8557#issuecomment-911863803

NVDA is not currently announcing additional <li> elements on a <ul> with role="alert" in Chrome.  It works in Edge with some re-arrangement of the role="alert" positioning.   Using span elements works in both, but is less semantic.

**Comment by mjbp** [comment]
Ouch. I can understand why adding role=alert to a ul overwriting the default role=list would confuse NVDA but not the if the alert is a containing div.

We could revert to the spans if it was testing well? The intended benefit of using semantic mark up was improved AT UX, so if that is borne out in testing I have no qualms in reverting.

Alternatively, if we really want to try to make the semantics happen we could test something like
<div role="list">
  <span role="listitem">Well crafted error message</span>
  <span role="listitem">Another well crafted error message</span>
 </div>

**Comment by sarah-storm** [comment]
Closing PR as per discussions around the error summary requirement

**Pull request closed without merging**
