### PR TITLE
Feature/cookie banner tracking

### PR DESCRIPTION
**Pull request by sarah-storm**
This feature adds in a stripped back version of the Measure component which tracks against the following spec:

[tracking-spec.docx](https://github.com/stormid/components/files/6350840/tracking-spec.docx)

### CODE REVIEW

**Comment by mjbp** [comment]
I agree with your Slack comment the tid probably shouldn't be in the package. I think it should be an option/setting of the cookie banner module. If we make the measurement functionality dependent on the tid then we can turn it off/on based on that.

You've done a great job of pruning the Measurement library so far but I reckon we could be more ruthless. I don't think that there's enough measurement-specific state to warrant a separate Store or state management/effects lifecycle. Without that part we could just call the URL composition and Measurement API functions directly and get the measurement part down to a few functions.

For testing, if we strip everything but the basic Measurement API URL composing and calls away then there's only a couple of test we need (I think). 

Similar to the measure library tests, we can check that the requests are valid using the Measurement API debugging endpoint https://developers.google.com/analytics/devguides/collection/protocol/v1/validating-hits. We'll still need John to manually check the GA account for a full e2e test but validation tests are a good safety net.

We'd also want to check that we're making the expected requests when the corresponding event happens. The requests to the API are made using navigator.beacon, so we can mock that and see if the expected requests are triggered when the banner events occur.

I've started doing something like this on another branch off this one and we can review early next week.

**Comment by mjbp** [comment]
An implementation and a few tests based on the above - stripping it right back, tid as an option is on this branch [https://github.com/stormid/components/tree/feature/cookie-banner-tracking-topiary/packages/cookie-banner.](https://github.com/stormid/components/tree/feature/cookie-banner-tracking-topiary/packages/cookie-banner.), which is a branch off this one. I added some resilience around getting the preferences cookie because of the JSON shape change.

Still need to hear back from John on the cm2/cm3 properties of the 'User saves preferences' event so that's only partially complete.

**Comment by mjbp** [comment]
I've added the cm2/cm3 parts, the new cm4 property, updated the tests, and added to the docs to include the measurement details. It's all on this branch.

Having the specific measurements baked into the module and not making them configurable in the settings bothers me a little, but I'm not convinced that the effort to abstract them is worth it given how we are going to use this, and if it becomes a requirement we can revisit in the next release? I am open to the opposing viewpoint!

**Comment by sarah-storm** [comment]
All makes sense Mick - thanks for fixing up!  I agree that starting with a fixed set of measurements makes sense for now. 
 The requirements haven't changed in the spec on a few projects to this point, and I'm not sure how much more would be required in the default banner template.  I think the way that you've separated those out would make the addition of that config doable later, and any other measurements from custom templates would be more case by case?

Cheers,
S

**Pull request merged**
